package com.netkoin.app.constants;

/**
 * Created by sid on 07/08/2016.
 */
public interface RequestConstants {
    int REQUEST_ID_POST_SIGNUP = 0;
    int REQUEST_ID_POST_SIGNIN = 1;

    int REQUEST_ID_GET_STORES = 2;
    int REQUEST_ID_GET_HOME_BANNER = 3;
    int REQIEST_ID_UPDATE_URSER_LOCATION = 4;
    int REQIEST_ID_CHECKIN_WALKIN = 5;
    int REQUEST_ID_GET_PRODUCT_BARCODES = 6;

    //for cateogries
    int REQUEST_ID_GET_CATEOGRIES_LIST = 7;
    int REQUEST_ID_GET_INDIVIDAUL_CATEGORY_DETAILS_BY_CAT_ID = 8;

    int REQUEST_ID_GET_ADS_BY_STORE_ID = 9;
    int REQUEST_ID_GET_STORE_FEATURED_BANNERS = 10;

    int REQUEST_ID_GET_PURCHASE_BARCODES = 11;
    int REQUEST_ID_GET_TRENDING_ADS = 12;

    int REQUEST_ID_GET_CATALOUGES = 13;

    //koin management
    int REQUEST_ID_POST_TRANSFER_KOINS = 14;
    int REQUEST_ID_GET_ACTIVITY_LOGS = 15;
    int REQUEST_ID_GET_TOTAL_KOIN = 16;
    int REQUEST_ID_GET_ACTIVITY_LOGS_UREAD_COUNT = 17;
    int REQUEST_ID_GET_ACTIVITY_LOGS_SET_READ_ALL = 18;


    int REQIEST_ID_CHECKIN_PRODUCTS = 19;
    int REQIEST_ID_CHECKIN_PURCHASES = 20;

    int REQIEST_ID_UPDATE_USER_LOCATION = 21;


    int REQUEST_ID_POST_FACEBOOK_SIGNIN = 22;

    int REQIEST_ID_REDEEM_KOIN = 23;

    int REQIEST_ID_POST_SETTINGS = 24;

    int REQUEST_ID_POST_GPLUS_SIGNIN = 25;

    int REQUEST_ID_POST_LOGOUT = 26;

    int REQUEST_ID_GET_NEARBY_STORE = 27;
    int REQUEST_ID_GET_LOCATION_GEOPOINTS_BY_PLACE_ID = 28;

}
